"""Write the generated includes before every build (docs/plan/05 §5.7, "Generated content").

- content/<subject>/_generated/prereq-map.md for every subject with a curriculum.yml, via
  `graph.py mermaid` (included by the subject's index.md);
- content/about/_generated/status-table.md, the dashboard table included by about/status.md.

`_generated/` is git-ignored, so stale copies can't be committed; `npm run generate` runs this,
and `dev` and `build` call it first.
"""

from __future__ import annotations

import argparse
import sys

import graph
from project import STATUS_RANK, Project, add_root_argument, display_path

STATUSES = ("draft", "reviewed", "verified")


def status_table(project: Project) -> str:
    g = graph.Graph(project)
    out = [
        "% Generated by scripts/generate.py from curriculum.yml and the pages' front matter.",
        "% Do not edit; it is rewritten before every build.",
        "",
    ]
    for cur in project.curricula:
        sp = project.subject_page(cur.subject)
        name = sp.title if sp and sp.title else cur.subject
        out += [f"### {name}", "", "| Chapter | Planned | Draft | Reviewed | Verified |", "|---|---:|---:|---:|---:|"]
        totals = [0, 0, 0, 0]
        written = []
        for k, (slug, title, topics, _line) in enumerate(cur.chapters, start=1):
            counts = [len(topics), 0, 0, 0]
            for label in topics:
                node = g.nodes[label]
                if node.written:
                    counts[1 + STATUS_RANK[node.status]] += 1
                    written.append((k, title, node))
            totals = [a + b for a, b in zip(totals, counts)]
            out.append(f"| {k}. {title} | {counts[0]} | {counts[1]} | {counts[2]} | {counts[3]} |")
        out += [f"| **All chapters** | **{totals[0]}** | **{totals[1]}** | **{totals[2]}** | **{totals[3]}** |", ""]
        if written:
            out += ["| Page | Chapter | Status |", "|---|---|---|"]
            for k, title, node in written:
                out.append(f"| [](#{node.label}) | {k}. {title} | {node.status} |")
        else:
            out.append(f"No topic pages have been written yet; all {totals[0]} are planned.")
        out.append("")
    if not project.curricula:
        out += ["No subject has a curriculum yet.", ""]
    return "\n".join(out)


def generate(project: Project) -> list:
    written = []
    for cur in project.curricula:
        path = project.root / cur.folder / "_generated" / "prereq-map.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(graph.mermaid(project, cur.subject), encoding="utf-8")
        written.append(path)
    path = project.root / "about" / "_generated" / "status-table.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(status_table(project), encoding="utf-8")
    written.append(path)
    return written


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_root_argument(ap)
    args = ap.parse_args(argv)
    for path in generate(Project(args.root)):
        print(f"generate.py: wrote {display_path(path)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
